# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 100
  reviewers:
  - ilovechai
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 25
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 5
